apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nature-client-tls
  namespace: default
spec:
  secretName: nature-client-tls-secret
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days before expiration
  commonName: nature-client.dev.com
  isCA: false
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
