name: One Click Deployment

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'main'  # Default branch name
      service:
        description: 'Service name'
        type: choice
        required: true
        options:
        - nature client
        - example log
        - uptime kuma
        default: nature client
      cluster:
        description: 'Cluster to deploy to'
        type: choice
        required: true
        options:
        - minikube
        - docker-desktop
        default: minikube

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Install Helm
        uses: azure/setup-helm@v3.3
        with:
          version: v3.14.0
      
      - name: Setup Cluster
        run: |
          if [ "${{ inputs.cluster }}" == "minikube" ]; then
            minikube start
            minikube addons enable ingress
            kubectl config use-context minikube
          elif [ "${{ inputs.cluster }}" == "docker-desktop" ]; then
            # Any setup specific to Docker Desktop
            echo "Docker Desktop setup"
          fi

      - name: Create Namespace
        run: |
          kubectl create namespace ${{ github.event.inputs.cluster }}-namespace


      - name: nature-client
        if: ${{ (inputs.service == 'nature client') }}
        run: |
          cd naturechart
          helm install chart3 . -n ${{ github.event.inputs.cluster }}-namespace

      - name: example log
        if: ${{ (inputs.service == 'example log') }}
        run: |
          cd examplechart
          helm install chart2 . -n ${{ github.event.inputs.cluster }}-namespace

      - name: uptime kuma
        if: ${{ (inputs.service == 'uptime kuma') }}
        run: |
          cd uptimechart
          helm install chart2 . -n ${{ github.event.inputs.cluster }}-namespace
