name: One Click Deployment

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'main'  # Default branch name
      service:
        description: 'Service name'
        type: choice
        required: true
        options:
        - nature client
        - example log
        - uptime kuma
        default: nature client

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Install Helm
        uses: azure/setup-helm@v3.3
        with:
          version: v3.14.0
          
      - name: setup minikube
        run: |
         minikube start

      - name: add ingress option
        run: |
         minikube addons enable ingress


      - name: nature-client
        if: ${{ (inputs.service == 'nature client') }}
        run: |
          cd naturechart
          helm install chart3 .

      - name: example log
        if: ${{ (inputs.service == 'example log') }}
        run: |
          cd examplechart
          helm install chart2 .

      - name: uptime kuma
        if: ${{ (inputs.service == 'uptime kuma') }}
        run: |
          cd uptimechart
          helm install chart2 .
